### ISSUE TITLE
Player cabling

### ISSUE THREAD

**Issue by ramdyne** [agdsn/battleswitch#1]
What is the cabling that the players are using for dropping the ammunition?  If you have one cable per attempt then you need a lot of cables, so I am a little confused :-)

I have it working, but the required cabling for the players is a little vague.

-- 
Bix

**Comment by wesx** [comment]
It is one cable per attempt. So you need some additional switches or modules to establish the connections. And yes this makes a lot of cables ;)
As far as I remember broadcast storms are not an issue there, so you can connect them as you want.

**Comment by Lodifice** [comment]
> As far as I remember broadcast storms are not an issue there
>

Just use different VLANs for the connection switch <-> client and
the cables for the shooting attempts.

**Comment by ramdyne** [comment]
That's about what we found out after just trying it all out. Expect an incoming pull request soon.

-- 
Andreas
